# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccexplorer < Formula
  desc ""
  homepage "https://github.com/cduggn/ccexplorer"
  version "0.5.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.5.12/ccExplorer_0.5.12_darwin_amd64.tar.gz"
      sha256 "f80c327dcbd74707b3c50f93f533fff241587934347514a3c11ddcd5ba41f994"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.5.12/ccExplorer_0.5.12_darwin_arm64.tar.gz"
      sha256 "94b6158db9fba4b9344befa5264bc7dc3c4546f941c6db415fa1ea2822687f7f"

      def install
        bin.install "ccexplorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.5.12/ccExplorer_0.5.12_linux_arm64.tar.gz"
      sha256 "b35255a66ab76139402b3d6c1c3a9f166aaf6018b29d3e7a3f152174abf49a23"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.5.12/ccExplorer_0.5.12_linux_amd64.tar.gz"
      sha256 "2a4777d974dc843bd15421bdcf354df42197f12377536d6e3a55f5b528f875bb"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.5.12/ccExplorer_0.5.12_linux_armv6.tar.gz"
      sha256 "64c3eaa3a60f09d62974c3fb97f9708583e4f974eb78bb09d4233935e0dde6d2"

      def install
        bin.install "ccexplorer"
      end
    end
  end
end
