# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccexplorer < Formula
  desc ""
  homepage "https://github.com/cduggn/ccexplorer"
  version "0.8.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.8.3/ccExplorer_0.8.3_darwin_amd64.tar.gz"
      sha256 "e187e7d003e0107a8c30bc443d9a85569265bb320ad336c7fffe3dfafb9df628"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.8.3/ccExplorer_0.8.3_darwin_arm64.tar.gz"
      sha256 "4a9bd45847084746ee459fa039c7fa9ec3cadc7f52dc28a11ebd8701b0bf5f90"

      def install
        bin.install "ccexplorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.8.3/ccExplorer_0.8.3_linux_amd64.tar.gz"
      sha256 "1c117683849e8ade1de0d90e2ba339d87ec91038366624d35121003f8c61db0d"
      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.8.3/ccExplorer_0.8.3_linux_armv6.tar.gz"
      sha256 "91233adcad1ccc808c6066692f400d88f0b88879a7d9c71b79561da34c0ff71d"
      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.8.3/ccExplorer_0.8.3_linux_arm64.tar.gz"
      sha256 "78e50955729e583997ed2bda6c7e5326655ada33a1e93e4f5d37827e9981256b"
      def install
        bin.install "ccexplorer"
      end
    end
  end
end
