# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cduggn < Formula
  desc ""
  homepage "https://github.com/cduggn/ccexplorer"
  version "0.1.1-rc7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc7/ccExplorer_0.1.1-rc7_darwin_amd64.tar.gz"
      sha256 "749397fa08ee399fc7abb5b4f998df011429f9748ed6e867c0e662314a4a25ef"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc7/ccExplorer_0.1.1-rc7_darwin_arm64.tar.gz"
      sha256 "21ab3dfdaa6feda07ffae40d5c39fd93c0fb3d84121c7acf787cb981b203a2de"

      def install
        bin.install "ccexplorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc7/ccExplorer_0.1.1-rc7_linux_arm64.tar.gz"
      sha256 "88deb1877fef9e9d7f1d3f8ecb5e20f8e33d8644786cb7e015a12de7b88cab9e"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc7/ccExplorer_0.1.1-rc7_linux_amd64.tar.gz"
      sha256 "5c1b6ddc24f63130318f6a6578930ff76337cf914e501f8fb4c0114db9670d12"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc7/ccExplorer_0.1.1-rc7_linux_armv6.tar.gz"
      sha256 "a70224f540b724311eea8c060e7a36babf30a13edc080de78725e3241fc1c478"

      def install
        bin.install "ccexplorer"
      end
    end
  end
end
