# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cduggn < Formula
  desc ""
  homepage "https://github.com/cduggn/ccExplorer"
  version "0.1.1-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc1/ccExplorer_0.1.1-rc1_darwin_amd64.tar.gz"
      sha256 "3b8162bb85b14d86caf1c4d10b605829ff4a67027c780157851267e0bcea8410"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc1/ccExplorer_0.1.1-rc1_darwin_arm64.tar.gz"
      sha256 "790dec52820851077b3a25b9526ac4d3a000dd6964c1d44698343fa7c189454e"

      def install
        bin.install "ccexplorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc1/ccExplorer_0.1.1-rc1_linux_armv6.tar.gz"
      sha256 "3a58c4289e5e3b75bdc19ab7cb4ff706c8acacdea3c0e717bd01c199d1ac8910"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc1/ccExplorer_0.1.1-rc1_linux_arm64.tar.gz"
      sha256 "da5af08b5082145d09edc6117d9bf38be585e601cf667b188ad55bc7840e2c0a"

      def install
        bin.install "ccexplorer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cduggn/ccExplorer/releases/download/v0.1.1-rc1/ccExplorer_0.1.1-rc1_linux_amd64.tar.gz"
      sha256 "a334ac4779e9e531e0ca57fd390635399f9ea6228f06a543d8f3618c52b0f975"

      def install
        bin.install "ccexplorer"
      end
    end
  end
end
